# Generated by Django 5.0.3 on 2024-03-13 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xglass', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodect',
            name='price',
            field=models.CharField(max_length=50),
        ),
    ]
