# Generated by Django 5.0.3 on 2024-03-16 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xglass', '0003_prodect_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prodect',
            name='id',
        ),
        migrations.AlterField(
            model_name='prodect',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='xglass.category'),
        ),
    ]
